### ISSUE TITLE
fix path to images in Helmi notebooks

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/qas2023#2]
for some reason the jpg image of Helmi isn't rendering

**Comment by JMuff22** [comment]
Is this referring to in github or on notebooks.csc.fi?

**Comment by wikfeldt** [comment]
just a github issue, nothing to do with CSC!

**Comment by wikfeldt** [comment]
fixed in ac9653cf7915c717acfa5263aed98fd8276c9259
